from typing import Protocol
from src.models.profile import Profile, ProfileCreation
import uuid


class ProfileRepository(Protocol):
    async def create_profile(self, profile: ProfileCreation) -> None: ...
    async def get_profile(self, id: uuid.UUID) -> Profile: ...
    async def get_profiles(self, ids: list[uuid.UUID]) -> list[Profile]: ...
    async def update_profile(self, profile: Profile) -> None: ...


class ProfileKafkaProducer(Protocol):
    async def send_create_profile(self, profile: ProfileCreation) -> None: ...
    async def send_complete_profile(self, profile: Profile) -> None: ...
    async def send_update_profile(self, profile: Profile) -> None: ...


class KeyCloak(Protocol):
    async def keycloak_create_user(self, profile: ProfileCreation) -> None: ...

    # !!! Is there a necessity to send a request when update or complete profile
