from aiokafka import AIOKafkaProducer
from src.models.profile import Profile


class KafkaProducerClient:
    def __init__(self, producer: AIOKafkaProducer) -> None: ...

    async def send_create_profile(self, profile: Profile) -> None: ...

    async def send_complete_profile(self, profile: Profile) -> None: ...

    async def send_update_profile(self, profile: Profile) -> None: ...
